CREATE SCHEMA IF NOT EXISTS `polarad_db`;

CREATE TABLE IF NOT EXISTS `polarad_db`.`users` (
uid VARCHAR(11),
fname VARCHAR(255),
lname VARCHAR(255) NOT NULL,
uname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
pword VARCHAR(255) NOT NULL,
bio LONGTEXT NOT NULL,
pic VARCHAR(255) NOT NULL,
since INT NOT NULL,
PRIMARY KEY(uid)
);

CREATE TABLE IF NOT EXISTS `polarad_db`.`posts` (
pid VARCHAR(11) NOT NULL,
uid VARCHAR(11) NOT NULL,
img_id VARCHAR(255) NOT NULL,
caption VARCHAR(255) NOT NULL,
PRIMARY KEY (pid)
);